backend:
  name: github
  repo: sheds-ui/sheds-ui.github.io
  branch: main
  base_url: https://sveltia-cms-auth.akash-sheds.workers.dev/
  automatic_deployments: false
media_folder: "/assets/images"
public_folder: "/assets/images"

collections:
  - label: "Updates"
    name: "updates"
    folder: "updates/"
    create: true
    editor:
      preview: true
    fields:
      - { label: "layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Teaser", name: "teaser", widget: "text", hint: "Short description of the post" }
      - { label: "Cover Image", name: "cover_image", widget: "image", required: false, hint: "Image for the carousel" }
      - { label: "Show post on carousel", name: "showcase", widget: "boolean", default: false, hint: "Showcase this post on the carousel" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Seminars"
    name: "seminars"
    folder: "seminars/2025/"
    create: true
    media_folder: "assets/seminars/2025/"
    public_folder: "assets/seminars/2025/"
    slug: "{{fields.date | date('YYYY-MM-DD')}}"
    fields:
      - { label: "layout", name: "layout", widget: "hidden", default: "seminar_page" }
      - { label: "#n", name: "n", widget: "number", value_type: "int", default: 225, step: 1 }
      - { label: "Title", name: "title", widget: "text" }
      - { label: "Speaker", name: "speaker", widget: "text" }
      - { label: "Speaker URL", name: "speaker_url", widget: "string" }
      - { label: "Speaker Bio", name: "speaker_bio", widget: "text" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Venue", name: "Venue", widget: "string" }
      - { label: "YouTube video id", name: "recorded_video", widget: "string", required: false, hint: "Add only if YouTube recording is Public" }
      - { label: "Image", name: "img", widget: "image", required: false, hint: "Add only if YouTube recording is Private or unavailable" }
      - { label: "Zoom link", name: "zoom_link", widget: "hidden", default: "https://us06web.zoom.us/j/83388976389?pwd=XcpO3GhLxsR14a7SVbPx33HQQa1jbt.1" }
      - { label: "Seminar abstract", name: "Topic_abstract", widget: "text" }
      - { label: "Slides", name: "slides", widget: "file", required: false, choose_url: false }
  - label: "Staff"
    name: "Staff"
    folder: "_people/staff/"
    create: true
    media_folder: "assets/images/people/staff/"
    public_folder: "assets/images/people/staff/"
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Position at CNI", name: "position_at_CNI", widget: "string" }
      - { label: "LinkedIn profile link", name: "linkedin", widget: "string", required: false }
      - { label: "Number at which to display", name: "importance", widget: "string" }
      - { label: "Image", name: "img", widget: "image" }
      - { label: "Is past staff?", name: "past", widget: "boolean", default: false }
      - { label: "Cap", name: "cap", widget: "string", required: false, hint: "Used to maintain the order of past staff. If someone exits now, put cap as 22" }
      - { label: "Category", name: "category", widget: "hidden", default: "Staff" }
  - label: "PhD Fellows"
    name: "PhD Fellows"
    folder: "_people/phd_fellows/"
    create: true
    media_folder: "assets/images/people/phd/"
    public_folder: "assets/images/people/phd/"
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Image", name: "img", widget: "image" }
      - { label: "LinkedIn profile link", name: "linkedin", widget: "string", required: false }
      - { label: "Website link", name: "redirect", widget: "string", required: false }
      - { label: "Category", name: "category", widget: "hidden", default: "Ph.D. Fellows/Scholars" }
      - { label: "Years", name: "years", widget: "string", hint: "e.g. [2024, 2025]" }
      - { label: "Advisor", name: "advisor", widget: "string" }
      - { label: "Department", name: "department", widget: "string" }
  - label: "MTech Fellows"
    name: "MTech Fellows"
    folder: "_people/mtech_fellows/"
    create: true
    media_folder: "assets/images/people/mtech/"
    public_folder: "assets/images/people/mtech/"
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Image", name: "img", widget: "image" }
      - { label: "LinkedIn profile link", name: "linkedin", widget: "string", required: false }
      - { label: "Website link", name: "redirect", widget: "string", required: false }
      - { label: "Category", name: "category", widget: "hidden", default: "M.Tech. Fellows/Scholars" }
      - { label: "Years", name: "years", widget: "string", hint: "e.g. [2024, 2025]" }
      - { label: "Advisor", name: "advisor", widget: "string" }
      - { label: "Department", name: "department", widget: "string" }
