backend:
  # Use netlify identity as backend
  #name: git-gateway
  #branch: main
  ### enable below lines for github integration ###
  name: github
  repo: sheds-ui/sheds-ui.github.io
  auth:
    github:
      clientId: Iv23liMusCNpknFlpGk3  # Use the Client ID you got from GitHub
      clientSecret: 13c5357d0b93189fcc9d97b0899a9c4ac5dbe3c0  # Use the Client Secret you got from GitHub
      scope: repo  # Define the required permissions (e.g., 'repo', 'user')
      apiUrl: https://api.github.com  # Default GitHub API URL
media_folder: "static/img"
public_folder: "static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Blog"
    name: "blog"
    folder: "posts/"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["Tags", "created", "from", "config.yml"]
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Quick Links"
        name: "links"
        file: "_data/quicklinks.yaml"
        fields:
          - label: Nav Items
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Description, name: desc, widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
